# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9123c4c7c07f076fe540637d6009c98ceef88019531a67c2770f6f3bf0f756f21f8daebff1ac814bac6278ded92a059aee28b85f0905ffe08ed8015d6938bdc4

test:
  secret_key_base: b6efa6cb83d055cd3f390c255cf83a212fd3a3f56ac31ace620b0846574f018e60e45da20f6ff1be5be5c536e5f4e187cce1f9cb473319c8bd7c4fc5bd311a07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
